### ISSUE TITLE
Review approach to fixing rng state for each test case

### ISSUE THREAD

**Issue by null-a** [pyro-ppl/brmp#16]
I copied the code for this verbatim from pyro in order get the tests working standalone.

* Tests were flakier than expected without this
* Assuming we continue to fix the seed, is there anything to do for numpyro?

**Comment by neerajprad** [comment]
>  is there anything to do for numpyro?

In NumPyro, we explicitly need to pass an rng key to inference algorithms and in fact to all distribution `.sample` methods, so it should be fully deterministic, unless we are using Python's random state to sample this value from.
