### ISSUE TITLE
Better error handling for unrecognized Ops

### ISSUE THREAD

**Issue by neerajprad** [pyro-ppl/brmp#54]
Currently a formula like `'y ~ a * b'` will throw an assertion error during code generation. Maybe we can recognize `*` as a valid Op but throw an NotImplementedError if we see it being used in the formula.

```  
File "/Users/npradhan/workspace/pyro_dev/brmp/brmp/formula.py", line 208, in rpn2ast
    assert len(out) == 1
AssertionError
```

**Comment by null-a** [comment]
Thanks for opening this. It's a good example of the kind of thing I had in mind when opening #7.

**Comment by neerajprad** [comment]
Sorry I missed that issue. Closing this as duplicate. Lets track this in #7.

**Comment by null-a** [comment]
> Sorry I missed that issue.

No problem!

> Lets track this in #7.

Here or there, either is fine with me.
