### ISSUE TITLE
Support for Poisson Regression

### ISSUE THREAD

**Issue by neerajprad** [pyro-ppl/brmp#56]
This should be straightforward to add - we just need to add a Poisson family, add log link function and define a default gamma prior, but maybe I'm oversimplifying?

Additionally, we also have a zero inflated Poisson in Pyro (and soon in NumPyro) so we can probably support that too at some point.

**Comment by neerajprad** [comment]
@null-a - Feel free to merge this if there is an existing issue tracking this.

**Comment by null-a** [comment]
> but maybe I'm oversimplifying?

No, I don't think so, for the most part it should be as you described I think. The only other thing that comes to mind that may need attention is [the logic](https://github.com/pyro-ppl/brmp/blob/f6a5d9d044d6be2a558aa16ec21fc5d5284c4642/brmp/model_pre.py#L9) that attempts to check whether the response family specified for a model matches the response column in the data. However, it's possible that for Poisson there'll be nothing to do -- [defining a family](https://github.com/pyro-ppl/brmp/blob/f6a5d9d044d6be2a558aa16ec21fc5d5284c4642/brmp/family.py#L61) with support `const(Type['IntegerRange'](0, None))` might do the trick. I'm happy to discuss in more detail if someone would like to do this and could use more pointers; also happy to add it myself if that helps.

**Comment by neerajprad** [comment]
Thanks, @null-a. I'll take this up - it will be good exercise in getting more acquainted with more of the internals.

**Comment by eb8680** [comment]
Added by @matteby in #84
